root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/server"
  entrypoint = "./tmp/main"
  include_ext = ["go", "yaml", "yml", "sql"]
  exclude_dir = ["tmp", "vendor", "internal/db"]
  delay = 500
  kill_delay = "1s"
  rerun = false
  rerun_delay = 500
  send_interrupt = true

[log]
  time = true
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
